### ISSUE TITLE
支持拖放切歌

### ISSUE THREAD

**Issue by ghost** [poboke/Miku#16]
感谢 UP主的 Miku，简直宅男福利啊～～我加了个 “拖放切歌（将音乐拖到miku上）” 的功能，希望 UP 主能够整合一下。
https://github.com/Xiaolong-Jin/Miku
PS： OS X 上有没有能够读取MMD的库，有的话希望 UP 主推荐下

**Comment by poboke** [comment]
非常感谢，已经加上这个功能了。
OS X 上读取MMD的库我倒没接触过。
