### ISSUE TITLE
请问插件项目需要怎么改成可调试的?

### ISSUE THREAD

**Issue by Butters2334** [poboke/Miku#21]
在下载插件模板之后,开发插件过程中需要不断的调试来实现功能,但是很多github插件项目clone下来之后发现都是只能编译,并不能调试;请问poboke知道怎么修改吗?

**Comment by poboke** [comment]
因为插件是Xcode启动时加载的bundle文件，必须是编译好的，所以插件工程不能动态调试。
目前可以通过输出log的方式来定位bug，所以开发插件是很麻烦的。

**Comment by Butters2334** [comment]
poboke你写了这么多插件居然都没有调试过!!

**Comment by Butters2334** [comment]
对的,插件是在Xcode启动时加载bundle文件来生效的,UDID的关联也证实了这点;但是同理,在编译好bundle文件之后启动一个新的Xcode不就可以调试了吗?比如:https://github.com/adad184/MMNavigatorFont 这个项目

**Comment by Butters2334** [comment]
现在我这边遇到问题是有很多优秀的插件项目都使用的这种形式的项目结构(不知道怎么称呼),单纯靠打log来理解项目还是很缓存的,所以一直在寻找能将这种项目结构变成可调试项目结构的办法~~~

**Comment by ookcode** [comment]
道理上是将执行改成xocde.app，即用xcode调试xcode，但是为什么我一调试这个就崩。（原谅我是看到miku才开始学习插件开发的XD

**Comment by poboke** [comment]
好吧，看来我被一些插件开发教程误导了，MMNavigatorFont确实可以动态调试，我用插件建一个新的插件也可以调试，可能工程某些地方被我改动了

**Comment by poboke** [comment]
找到了，`Edit Scheme`里，`Executable`选择`Xcode.app`.

![executable](https://cloud.githubusercontent.com/assets/4415086/12389035/668db9dc-be11-11e5-81bb-b223460c53bb.png)

**Comment by poboke** [comment]
原因是我的工程里ignore了`xcuserdata`里的个人信息，所以运行工程时没有scheme文件去指定Xcode.app运行。

**Comment by poboke** [comment]
@ookcode 你装了ActivatePowerMode吧，因为里面的类名重复了，看来我要改一下文件名

**Comment by ookcode** [comment]
@poboke 是的😂

**Comment by Butters2334** [comment]
@poboke @ookcode 我找到了,不能调试的插件项目虽然可以选择xcode.app编译,但是在运行状态还是会崩溃,需要将Edit Scheme > Run > Options 下面 "Enable user interface debugging"一项取消掉;

**Comment by ookcode** [comment]
@anmac 真的耶，可以调试了，Nice job~👍

**Comment by poboke** [comment]
@anmac 🎉可以调试了，应该可以节省一半的开发时间
