### ISSUE TITLE
编辑框里面会有条竖线，但竖线右边的部分还是可以编辑的

### ISSUE THREAD

**Issue by tabedoc** [poboke/Miku#23]
<img width="945" alt="2016-01-18 10 24 52" src="https://cloud.githubusercontent.com/assets/8002952/12393759/bc13bc64-be32-11e5-9ece-46a5fca2fb48.png">

**Comment by tabedoc** [comment]
竖线右侧部分是可以编辑到的，是不是你这个view的边框啊？

**Comment by poboke** [comment]
这个跟插件无关吧，看起来好像是你在偏好设置里勾上了这个

![setting](https://cloud.githubusercontent.com/assets/4415086/12394841/3fd24538-be39-11e5-8e9e-f812055a8b43.png)

**Comment by tabedoc** [comment]
不好意思，乌龙
